//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Apps")
export class AppsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Appname: string;

@Column({nullable: true})
Developer: string;

@Column({nullable: true})
Category: string;

@Column({nullable: true})
Numberofentities: string;

@Column({nullable: true})
Id: string;


}
